### ISSUE TITLE
Not able to run this project

### ISSUE THREAD

**Issue by bismoy2013** [twitter/ambrose#164]
Tried running this :  cd pig/target/ambrose-pig-$VERSION-bin/ambrose-pig-$VERSION
AMBROSE_PORT=8080 ./bin/pig-ambrose -f script.pig

Getting this error :

Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2014-11-30 13:33:16,813 [main] ERROR org.apache.pig.Main - ERROR 2997: Encountered IOException. File script.pig does not exist
Details at logfile: /home/bismoy/Music/ambrose/pig/target/ambrose-pig-0.3.1-SNAPSHOT-bin/ambrose-pig-0.3.1-SNAPSHOT/bin/pig_1417334596354.log
[Shutdown] INFO org.mortbay.log - Shutdown hook executing

**Comment by sagemintblue** [comment]
You are meant to run the above command on your own pig script. Running it on a non-existent script will produce the error you observed. This is expected behavior.
